[package]
name = "xextra"
version = "2.0.0"
edition = "2021"
description = "Variety of utilities for X-windowing."
authors = ["1e1001"]
repository = "https://github.com/1e1001/xextra"
license = "EUPL-1.2-or-later"

[features]

[dependencies.xcb]
version = "1.5.0"
features = ["xkb"]

[dependencies.thiserror]
version = "2.0.12"

[dependencies.clap]
version = "4.5.35"
features = ["derive"]

[dependencies.foldhash]
version = "0.1.5"

[dependencies.weak-table]
version = "0.3.2"

[dependencies.libc]
version = "0.2.171"

[dependencies.multiline-logger]
version = "0.1.0"
features = ["backtrace"]

[dependencies.iter-debug]
version = "1.0.0"

[dependencies.tokio]
version = "1.44.1"
# single-thread runtime only
features = ["io-util", "macros", "net", "rt", "signal", "sync", "time"]

[dependencies.cpal]
version = "0.15.3"
[dependencies.hound]
version = "3.5.1"
[dependencies.claxon]
version = "0.4.3"
[dependencies.lewton]
version = "0.10.2"

# still 20 times larger than the C version but oh well
[profile.release]
strip = true
opt-level = "s"
lto = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(rust_analyzer)'] }

[lints.clippy]
# pedantic
pedantic = { level = "warn", priority = -1 }
similar_names = "allow"
must_use_candidate = "allow"
allow_attributes_without_reason = "deny"

# restriction
absolute_paths = "warn"
alloc_instead_of_core = "warn"
allow_attributes = "warn"
as_underscore = "warn"
assertions_on_result_states = "warn"
clone_on_ref_ptr = "warn"
dbg_macro = "warn"
default_union_representation = "warn"
empty_drop = "warn"
empty_structs_with_brackets = "warn"
filetype_is_file = "warn"
fn_to_numeric_cast_any = "warn"
format_push_string = "warn"
get_unwrap = "warn"
if_then_some_else_none = "warn"
impl_trait_in_params = "warn"
missing_assert_message = "warn"
missing_asserts_for_indexing = "warn"
multiple_inherent_impl = "warn"
multiple_unsafe_ops_per_block = "warn"
mutex_atomic = "warn"
panic_in_result_fn = "warn"
print_stderr = "warn"
print_stdout = "warn"
pub_without_shorthand = "warn"
rc_buffer = "warn"
rc_mutex = "warn"
redundant_type_annotations = "warn"
rest_pat_in_fully_bound_structs = "warn"
semicolon_outside_block = "warn"
shadow_unrelated = "warn"
single_char_lifetime_names = "warn"
str_to_string = "warn"
string_to_string = "warn"
tests_outside_test_module = "warn"
todo = "warn"
try_err = "warn"
undocumented_unsafe_blocks = "warn"
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
unneeded_field_pattern = "warn"
unseparated_literal_suffix = "warn"
unwrap_in_result = "warn"
