# Example configuration file, listing all properties and their default values

# Section: global settings
:
	# Text: path for the control socket
	control: /run/user/\u/xextra control

# Section: Window swallowing
swallow: 1
	# TextList: process names to treat as terminals
	terminal: alacritty
	# TextList: process names to exclude from swallowing their parent
	immune:
# Section: Audio bell
bell: 1
	# Text: Path to the bell sample,
	# relative to the folder where xextra is executed.
	# Default is a builtin sound effect.
	# Supported file formats: wav, ogg, flac
	path:
	# Float: volume fraction
	volume: 0.5
